import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const TopNav = () => {
  return (
    <nav className="flex items-center justify-between gap-4 p-4 text-2xl border-b-2">
      <div>Gallery</div>
      <div>Sign In</div>
    </nav>
  )
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className=" flex flex-col gap-4">
        <TopNav />
        {children}
        </body>
    </html>
  );
}
